import sys
sys.path.append("../")
import fire
import torch 
import pandas as pd
import math 
from robot_scripts.optimize import Optimize
from robot.diverse_oas_objective import DiverseOASObjective
from constants import (
    PATH_TO_VAE_STATE_DICT, 
    PATH_TO_ANTIGEN_PDB, 
    WORK_DIR,
    PATH_TO_INITILIZATION_DATA
)

class DiverseOASOptimization(Optimize):
    """
    Run LOL-ROBOT Optimization for any OAS seq Optimization Task 
    using the pretrained OAS VAE 
    Args:
        path_to_vae_statedict: Path to state dict of pretrained VAE,
        max_string_length: Limit on string length that can be generated by VAE 
        (without a limit we can run into OOM issues)
    """
    def __init__(
        self,
        path_to_vae_statedict: str=PATH_TO_VAE_STATE_DICT,
        max_string_length: int=1024,
        optimize_pose=False,
        max_allowed_edit_dist=20,
        **kwargs
    ):
        self.optimize_pose=optimize_pose
        self.max_allowed_edit_dist=max_allowed_edit_dist
        self.path_to_vae_statedict = path_to_vae_statedict
        self.max_string_length = max_string_length

        super().__init__(**kwargs)

        # add args to method args dict to be logged by wandb
        self.method_args['molopt'] = locals()
        del self.method_args['molopt']['self']

    def initialize_objective(self):
        # initialize molecule objective
        self.objective = DiverseOASObjective(
            task_id=self.task_id,
            path_to_vae_statedict=self.path_to_vae_statedict,
            max_string_length=self.max_string_length,
            anitgen_pdb_path=PATH_TO_ANTIGEN_PDB,
            work_dir=WORK_DIR,
            optimize_pose=self.optimize_pose,
            max_allowed_edit_dist=self.max_allowed_edit_dist,
        )

        return self

    def compute_train_zs(
        self,
        bsz=64
    ):
        init_zs = []
        # make sure vae is in eval mode 
        self.objective.vae.eval() 
        n_batches = math.ceil(len(self.init_train_x)/bsz)
        for i in range(n_batches):
            xs_batch = self.init_train_x[i*bsz:(i+1)*bsz] 
            zs, _ = self.objective.vae_forward(xs_batch)
            init_zs.append(zs.detach().cpu())
        init_zs = torch.cat(init_zs, dim=0)
        # now save the zs so we don't have to recompute them in the future:
        state_dict_file_type = self.objective.path_to_vae_statedict.split('.')[-1] # usually .pt or .ckpt
        path_to_init_train_zs = self.objective.path_to_vae_statedict.replace(f".{state_dict_file_type}", '-train-zs.csv')
        zs_arr = init_zs.cpu().detach().numpy()
        pd.DataFrame(zs_arr).to_csv(path_to_init_train_zs, header=None, index=None) 

        return init_zs

    def load_train_data(self):
        ''' Load in or randomly initialize self.num_initialization_points
            total initial data points to kick-off optimization 
            Must define the following:
                self.init_train_x (a list of x's)
                self.init_train_y (a tensor of scores/y's)
                self.init_train_z (a tensor of corresponding latent space points)
            '''
        df = pd.read_csv(PATH_TO_INITILIZATION_DATA)
        train_x_seqs = df['seq'].values.tolist()
        train_y = torch.from_numpy(df[self.task_id].values).float() 
        # Here we assume init_data.csv has columsn 'seq', 'dfire', 'dfire2', 'cpydock'
        self.num_initialization_points = min(self.num_initialization_points, len(train_x_seqs))
        self.load_train_z()
        self.init_train_x = train_x_seqs[0:self.num_initialization_points]
        train_y = train_y[0:self.num_initialization_points]
        self.init_train_y = train_y.unsqueeze(-1)
        # self.init_train_c = self.objective.compute_constraints(self.init_train_x)
        return self 

    def load_train_z(
        self,
    ):
        state_dict_file_type = self.path_to_vae_statedict.split('.')[-1] # usually .pt or .ckpt
        path_to_init_train_zs = self.path_to_vae_statedict.replace(f".{state_dict_file_type}", '-train-zs.csv')
        # if we have a path to pre-computed train zs for vae, load them
        try:
            zs = pd.read_csv(path_to_init_train_zs, header=None).values
            # make sure we have a sufficient number of saved train zs
            assert len(zs) >= self.num_initialization_points
            zs = zs[0:self.num_initialization_points]
            zs = torch.from_numpy(zs).float()
        # otherwisee, set zs to None 
        except: 
            zs = None 
        self.init_train_z = zs 
        return self 


if __name__ == "__main__":
    fire.Fire(DiverseOASOptimization)
